# Generated by Django 2.0.8 on 2018-09-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diretor', models.CharField(max_length=200)),
                ('nome_filme', models.CharField(max_length=200)),
                ('elenco', models.CharField(max_length=200)),
                ('produtora', models.CharField(max_length=200)),
                ('roterista', models.CharField(max_length=200)),
            ],
        ),
    ]
